name: Test

on:
  push:
    branches:
      - $default-branch
      - development
      - master
  # Run tests for any PRs
  pull_request:
  workflow_dispatch:

jobs:
  macos:
    name: Running tests on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
    runs-on: ${{ matrix.os }}
    steps:

      - name: Git clone repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install shellcheck
        run: brew install shellcheck

      - name: install cpanm and Date::Parse
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: Date::Parse

      - name: Run the tests
        run:  |
          uname -a \
          && make test

  linux:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Running tests on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'debian:9'
          - 'debian:10'
          - 'debian:testing'
          - 'ubuntu:16.04'
          - 'ubuntu:18.04'
          - 'ubuntu:20.04'
          - 'ubuntu:20.10'
          - 'alpine:3.13'
          - 'alpine:edge'
          - 'centos:7'
          - 'centos:8'
          - 'fedora:32'
          - 'fedora:33'
          - 'fedora:34'
          - 'fedora:rawhide'
        include:
          - distro: 'debian:testing'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install nmap shellcheck curl sudo perl make bzip2 file
          - distro: 'debian:10'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install nmap shellcheck curl sudo perl make bzip2 file
          - distro: 'debian:9'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install nmap shellcheck curl sudo perl make bzip2 file
          - distro: 'ubuntu:20.10'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install nmap shellcheck curl sudo perl make bzip2 file
          - distro: 'ubuntu:16.04'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install nmap shellcheck curl sudo perl make bzip2 file
          - distro: 'ubuntu:18.04'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install nmap shellcheck curl sudo perl make bzip2 file
          - distro: 'ubuntu:20.04'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install nmap shellcheck curl sudo perl make bzip2 file
          - distro: 'alpine:edge'
            pre: >-
              apk update &&
              apk upgrade &&
              apk add -U bash &&
              apk add nmap shellcheck curl sudo perl make wget bzip2 file
          - distro: 'alpine:3.13'
            pre: >-
              apk update &&
              apk upgrade &&
              apk add -U bash &&
              apk add nmap shellcheck curl sudo perl make wget bzip2 file
          - distro: 'fedora:rawhide'
            pre: >-
              dnf upgrade -y &&
              dnf install -y nmap ShellCheck curl sudo perl make bzip2 file
          - distro: 'fedora:34'
            pre: >-
              dnf upgrade -y &&
              dnf install -y hostname &&
              dnf install -y nmap ShellCheck curl sudo perl make bzip2 file
          - distro: 'fedora:33'
            pre: >-
              dnf upgrade -y &&
              dnf install -y hostname &&
              dnf install -y nmap ShellCheck curl sudo perl make bzip2 file
          - distro: 'fedora:32'
            pre: >-
              dnf upgrade -y &&
              dnf install -y hostname &&
              dnf install -y nmap ShellCheck curl sudo perl make bzip2 file
          - distro: 'centos:7'
            pre: >-
              yum upgrade -y &&
              yum install -y nmap curl sudo perl make bzip2 file &&
              scversion="stable"; curl -Ls "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv && cp "shellcheck-${scversion}/shellcheck" /usr/bin/
          - distro: 'centos:8'
            pre: >-
              dnf upgrade -y &&
              dnf install -y nmap curl sudo perl make bzip2 file &&
              scversion="stable"; curl -Ls "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv && cp "shellcheck-${scversion}/shellcheck" /usr/bin/
    steps:
      - name: Git clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run the tests on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          echo $PRE > ./prep-cmd.sh
          docker run --network host -w /check_letsdebug -v ${PWD}:/check_letsdebug ${{ matrix.distro }} \
              /bin/sh -c 'sh ./prep-cmd.sh \
              && curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus \
              && cpanm --sudo install Date::Parse \
              && uname -a \
              && make test \
              && if command -v shellcheck > /dev/null 2>&1  ; then shellcheck ./check_letsdebug ; fi'

  rpm:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Running RPM tests on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'centos:7'
          - 'centos:8'
          - 'fedora:32'
          - 'fedora:33'
          - 'fedora:34'
          - 'fedora:rawhide'
        include:
          - distro: 'fedora:rawhide'
            pre: >-
              dnf install -y ShellCheck curl sudo make bzip2 bind-utils hostname rpm-build
          - distro: 'fedora:34'
            pre: >-
              dnf install -y hostname &&
              dnf install -y ShellCheck curl sudo make bzip2 bind-utils rpm-build
          - distro: 'fedora:33'
            pre: >-
              dnf install -y hostname &&
              dnf install -y ShellCheck curl sudo make bzip2 bind-utils rpm-build
          - distro: 'fedora:32'
            pre: >-
              dnf install -y hostname &&
              dnf install -y ShellCheck curl sudo make bzip2 bind-utils rpm-build
          - distro: 'centos:7'
            pre: >-
              yum install -y curl sudo make bzip2 rpm-build &&
              scversion="stable"; curl -Ls "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv && cp "shellcheck-${scversion}/shellcheck" /usr/bin/
          - distro: 'centos:8'
            pre: >-
              dnf install -y curl sudo make bzip2 rpm-build &&
              scversion="stable"; curl -Ls "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv && cp "shellcheck-${scversion}/shellcheck" /usr/bin/
    steps:
      - name: Git clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build the RPM on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          echo $PRE > ./prep-cmd.sh
          docker run --network host -w /check_letsdebug -v ${PWD}:/check_letsdebug ${{ matrix.distro }} \
              /bin/sh -c 'sh ./prep-cmd.sh \
              && uname -a \
              && make rpm'
