name: Test

on:
  push:
    branches:
      - $default-branch
      - main
  # Run tests for any PRs
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  macos:
    name: Running tests on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - macos-13
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:

      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Run the tests
        run:  |
          uname -a \
          && make test

  linux:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Running tests on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'debian:latest'
          - 'ubuntu:latest'
          - 'alpine:latest'
          - 'fedora:latest'
        include:
          - distro: 'debian:latest'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install nmap shellcheck curl sudo perl make bzip2 file
          - distro: 'ubuntu:latest'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install nmap shellcheck curl sudo perl make bzip2 file
          - distro: 'alpine:latest'
            pre: >-
              apk update &&
              apk upgrade &&
              apk add -U bash &&
              apk add nmap shellcheck curl sudo perl make wget bzip2 file
          - distro: 'fedora:latest'
            pre: >-
              dnf upgrade -y &&
              dnf install -y hostname &&
              dnf install -y nmap ShellCheck curl sudo perl make bzip2 file
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run the tests on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          echo $PRE > ./prep-cmd.sh
          docker run --network host -w /check_letsdebug -v ${PWD}:/check_letsdebug ${{ matrix.distro }} \
              /bin/sh -c 'sh ./prep-cmd.sh \
              && uname -a \
              && make test \
              && if command -v shellcheck > /dev/null 2>&1  ; then shellcheck ./check_letsdebug ; fi'

  rpm:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Running RPM tests on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'fedora:39'
          - 'fedora:40'
        include:
          - distro: 'fedora:40'
            pre: >-
              dnf install -y hostname &&
              dnf install -y ShellCheck curl sudo make bzip2 rpm-build
          - distro: 'fedora:39'
            pre: >-
              dnf install -y hostname &&
              dnf install -y ShellCheck curl sudo make bzip2 rpm-build
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build the RPM on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          echo $PRE > ./prep-cmd.sh
          docker run --network host -w /check_letsdebug -v ${PWD}:/check_letsdebug ${{ matrix.distro }} \
              /bin/sh -c 'sh ./prep-cmd.sh \
              && uname -a \
              && make rpm'
